# The Docker image that will be used to build your app
image: python:3.10

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - pip install -r requirements.txt

test:
  stage: test

deploy:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - gunicorn -c gunicorn_config.py app:app
  only:
    - master


