# The Docker image that will be used to build your app
image: python:3.10

pages:
  script:
  - pip install --no-cache-dir -r requirements.txt
  - FLASK_APP=app.py
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
